name: iOS Build & Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/.swiftpm
          key: ${{ runner.os }}-swiftpm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-swiftpm-

     - name: Build
  run: |
    xcodebuild clean build \
      -scheme YourAppScheme \
      -project YourApp.xcodeproj \
      -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
      CODE_SIGNING_ALLOWED=NO
      - name: Run Unit Tests
        run: |
          xcodebuild test             -scheme YourAppScheme             -project YourApp.xcodeproj             -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5'             CODE_SIGNING_ALLOWED=NO

      - name: Archive app
        run: |
          xcodebuild archive             -scheme YourAppScheme             -project YourApp.xcodeproj             -archivePath $PWD/build/YourApp.xcarchive             CODE_SIGNING_ALLOWED=NO

      - name: Export IPA
        run: |
          xcodebuild -exportArchive             -archivePath $PWD/build/YourApp.xcarchive             -exportOptionsPlist ExportOptions.plist             -exportPath $PWD/build

      - name: Upload build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Build
          path: build
